version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: yummy_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yummy_recipes
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: yummy_backend
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/uploads:/usr/src/app/uploads
    ports:
      - "8080:8080"
    command: npm run dev

volumes:
  db_data:
